export const INITIALIZE_CATEGORIES = 'INITIALIZE_CATEGORIES';
export const INITIALIZE_CATEGORY_FORM = 'INITIALIZE_CATEGORY_FORM';
export const SET_CATEGORY_FORM_FIELD = 'SET_CATEGORY_FORM_FIELD';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
