export const INITIALIZE_POSTS = 'INITIALIZE_POSTS';
export const INITIALIZE_POST_STATE = 'INITIALIZE_POST_STATE';
export const SET_POST_FORM_FIELD = 'SET_POST_FORM_FIELD';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
