import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { gql, useQuery } from '@apollo/client';

const AllPostsQuery = gql`
  query {
    posts {
      id
      title
      slug
    }
  }
`;

const Home: NextPage = () => {
  const { data, error, loading } = useQuery(AllPostsQuery);

  if (loading) {
    return <p>Loading...</p>;
  }

  if (error) {
    return <p>Something went wrong.</p>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>T7andollar</h1>
        <h2>Posts</h2>
        <ul>
          {data.posts.map((post) => (
            <li key={post.id}>{post.title}</li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
